### ISSUE TITLE
Servo: host file editor

### ISSUE THREAD

**Issue by arecker** [arecker/msg#1]
It would be sweet to have a servo for modifying the server's host file.

``` yml
servos:
  - host:
      add:
        - mynewwebsite.com: 127.0.0.1
      remove:
        - myoldsite.com: 127.0.0.1
```

Where
- `add` lists entries to be added if absent
- `remove` lists entries to be removed if present

It would also be sweet if there was a shortcut configuration that looked like this:

``` yml
servos:
  - host: mynewwebsite.com
```

That would ideally just add the host associated to the servo in the list.
