### ISSUE TITLE
Servo: ssh access manager

### ISSUE THREAD

**Issue by arecker** [arecker/msg#2]
It would be sweet to have a servo to bootstrap an SSH connection.  At first, it could look something like this

``` yml
servos:
  - ssh:
      key: '/home/$(whoami)/.ssh/id_rsa.pub' # default
      port: 22 # default
```
