### ISSUE TITLE
Servo: static site deployer

### ISSUE THREAD

**Issue by arecker** [arecker/msg#3]
It would be sweet to have a servo take care of deploying static websites

``` yml
servos:
  - install:
      packages:
        - nginx
  - host: mynewwebsite.com
  - site:
      server: nginx
      host: mynewwebsite.com
      root: /var/web/www/mynewwebsite
      git: https://github.com/mynewwebsite # git repo
      payload: /temp/mynewwebsite.tar.gz # local payload
```
